version: '3.1'

services:
  postgres:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    volumes:
      - pg:/var/lib/postgresql

volumes:
  pg:
    driver: local