version: '3.1'

services:
  postgres:
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    volumes:
      - pg:/var/lib/postgresql

volumes:
  pg:
    driver: local